name: Trivy Scan Juice Shop

on: [push, workflow_dispatch]

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Trivy
      run: |
        sudo apt install wget -y
        wget https://github.com/aquasecurity/trivy/releases/latest/download/trivy_0.61.0_Linux-64bit.deb
        sudo dpkg -i trivy_0.61.0_Linux-64bit.deb

    - name: Run Trivy scan on Juice Shop Docker image
      run: |
        trivy image bkimminich/juice-shop --format json --output trivy-results.json

    - name: Upload Trivy scan results
      uses: actions/upload-artifact@v4
      with:
        name: trivy-scan-results
        path: trivy-results.json
