name: OWASP ZAP Scan

  on: [push]

  jobs:
    zap_scan:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout Code
          uses: actions/checkout@v2

        - name: OWASP ZAP Scan
          uses: zaproxy/action-full-scan@v0.4.0
          with:
            target: 'https://juice-shop-n0kl.onrender.com'  #Juice-shop web application scan only
            allow_issue_writing: false
